
map_image_save_dir: /root/catkin_ws/src/occ_grid_mapping/map.png
map_config_save_dir: /root/catkin_ws/src/occ_grid_mapping/map.yaml

map:
  sizex: 2000
  sizey: 2000
  initx: 1000
  inity: 1000
  cell_size: 0.05
  # frame_id: odom
  
robot_laser:
  x: 0.0
  y: 0.0
  theta: 0.0

sensor_model:
  P_occ: 0.95
  P_free: 0.45
  P_prior: 0.5
