
map_image_save_dir: /root/catkin_ws/src/occ_grid_mapping/map.png
map_config_save_dir: /root/catkin_ws/src/occ_grid_mapping/map.yaml

map:
  sizex: 600
  sizey: 600
  initx: 300
  inity: 300
  cell_size: 0.05
  # frame_id: odom
  
robot_laser:
  x: 0.0
  y: 0.0
  theta: 0.0

sensor_model:
  P_occ: 0.8
  P_free: 0.4
  P_prior: 0.5
