
map_image_save_dir: /root/occ_map/map.png
map_config_save_dir: /root/occ_map/map.yaml

map:
  sizex: 300
  sizey: 300
  initx: 150
  inity: 150
  cell_size: 0.05
  # frame_id: odom
  
robot_laser:
  x: 0.0
  y: 0.0
  theta: 0.0

sensor_model:
  P_occ: 0.7
  P_free: 0.4
  P_prior: 0.5
